image: alpine:latest

pages:
  stage: deploy
  script:
  - echo "starting static noop script"
  - mkdir public
  - cp -rp docs public
  artifacts:
    paths:
    - public
  only:
  - master
